### PR TITLE
cvxsimulator in requirements

### PR DESCRIPTION
**Pull request by tschm**

### CODE REVIEW

**Comment by tschm** [comment]
Maybe for later. Would help to focus the code better on the actual Markowitz experiments. @kasperjo also has done good work with the simulator. Introduces a bunch of dependencies. Note that I have a copy of quantstats in a folder of cvxsimulator to avoid dealing with this dependency with only sporadic updates...

**Review by kasperjo — APPROVED** [review]

**Comment by tschm** [comment]
Recent versions of cvxSimulator only depend on plotly. I have made the dependency on quantstats an optional extra. In case you are interested in performance metrics you can install that, too. However, a lot of users would have something for their metrics in place already.

**Comment by phschiele** [comment]
Thanks for the updates to `cvxSimulator` @tschm!
I still think it is not necessary to add the dependency in this repo, since we don't use it at all.
So either we rewrite the backtest using cvxsimulator, or close this PR.
I'd be in cautious rewriting the backtest, since these are the numbers that we also reported in the paper, and changes in the setup might lead to (small) deviations.

**Comment by tschm** [comment]
of course, the plan would be to first include the dependency and then refactor the backtest...  It could save some code and put emphasis on the core message of the paper.

**Pull request closed without merging**
