### PR TITLE
11 remove the book completely

### PR DESCRIPTION
**Pull request by tschm**

### CODE REVIEW

**Comment by tschm** [comment]
I would like to keep a minimal set of tests and some hygienic pre-commit measures...

**Comment by tschm** [comment]
@kasperjo @phschiele Call at 10am?

**Comment by kasperjo** [comment]
> @kasperjo @phschiele Call at 10am?

I’m at breakfast with family! Won’t make it unfortunately:(

**Comment by tschm** [comment]
I have merged the branch of @phschiele into this branch. Hence same Markowitz.py

**Review by phschiele — APPROVED** [review]
LGTM

**Pull request merged**
